<?php

/**
 * Implements hook_menu()
 */
function tripal_hq_menu() {


  /**
   * Admin can configure which emails get sent out, more stuff?
   */
  $items['/admin/tripal/tripal_hq'] = [
    'title' => 'Tripal HQ settings',
    'page callback' => 'drupal_get_form',
    'file' => 'includes/tripal_hq_admin_settings.form.inc',
    'access arguments' => ['admin content'],
  ];


  $items['/tripal_hq/submission_dash/'] = [];

  $items['/tripal_hq/admin_dash/'] = [];

  return $items;
}


/**
 * Implements hook_permission().
 */

function tripal_hq_permission() {
  return [
    'access tripal_hq admin' => [
      'title' => t('Administer tripal_HQ content'),
      'description' => t('Allow admins to view and approve content.'),
    ],
    'access tripal_hq user' =>
      [
        'title' => t('Create Tripal content requests'),
        'description' => t('Allow users to submit content requests, and view their content dashboard'),
      ],
  ];
}
